package: tracks
version: '4.0.0'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/tracks


requires:
    php:
        version: '>=8.1'
    redaxo: ^5.18.0

page:
    title: translate:blaupause_title
    hidden: true

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
